### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by pahaz** [miyakogi/wdom#1]

**Comment by pahaz** [comment]
Sorry, I pressed submit by mistake. 

I think Python really needs good web based GUI library. But the way with reproduce Dom library is not so good. 

Attempt to move logic processing JS code in a normal Python never ends well. Dom and js technologies are developing too fast. And there is nothing wrong to use js for the interface logic.

It seems to me that the value of your project to provide an opportunity to move Web project in the desktop app. 

I would be more focused on this area.

It's my feedback. 

What's your opinion on this point?

**Comment by miyakogi** [comment]
Thank you very much for your comment!

Actually, the first target of mine (and this project) is users writing desktop applications (or simple tools) with PyQt or wxPyhton, not web developers. This library is not intended to help users to write web-applications and desktop applications in the same code base, or to port web applications to python's desktop applications.

More concretely, one of my targets is users using python for data analysis or experiments. Scientific libraries like numpy, scipy and pandas are necessary for their work, so they need to write logic by python and execute their code in python. (I think porting these libraries to JS is too heavy.)

Python lacks good GUI library _and_ good plotting libraries well integrated with GUIs, however [JS has](https://en.wikipedia.org/wiki/Comparison_of_JavaScript_charting_frameworks). I think these users are not so familiar with JS, so writing interfaces between python and JS and using plotting libraries of JS is not easy. I would like to improve this situation.

The reason why I chose DOM API is because it's well standardized and used widely. When making a GUI library based on web/browser technology, finally GUI elements are rendered as DOM on the browser. Why do we need to make new, different APIs for this purpose?

As I wrote above, some users may not be familiar with DOM API, but in future, they may need to use JS. At that time, I hope the experience they used wdom helps them to learn JS. Of course, users who are already familiar to JS and DOM, can start using wdom more easily, since they don't need to learn new APIs from zero.

> Attempt to move logic processing JS code in a normal Python never ends well. 

You might have misunderstanding about this library, and sorry, its fully my fault, I have to prepare more documents... WDOM does not execute JS on python, or convert JS to python, just execute (maybe short) JS code on browsers when triggered by python. This feature is intended to help users to easily use JS libraries for plotting or showing modal windows, and so on.

I'm sorry for long reply, but I'm so happy to have your comment, and, if you have had an interest on this project, its great pleasure for me :blush:

Thank you!
